In [21]:

# Step 1: Import Libraries

import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer


In [22]:

# Step 2: Data Ingestion

df = pd.read_csv("Reviews.csv", nrows=50000)

print("First 50,000 rows loaded successfully.")
print("Total Rows:", len(df))


First 50,000 rows loaded successfully.
Total Rows: 50000


In [23]:

# Step 3: Text Selection

light_reviews = df[df["Text"].str.contains(r"\blight\b", case=False, na=False)]

print(light_reviews["Text"].head(20))


2      This is a confection that has been around a fe...
238    A very delicate green tea with a smooth light ...
269    This is a delicious sugar. It has a pretty lig...
396    Arrowhead Mills Buttermilk Pancake mix is my f...
404    A good tasting light chip that has some value ...
462    Kettle Chips flavors can be hit or miss.  Some...
466    I'm addicted to salty and tangy flavors, so wh...
467    These Honey Dijon chips bring a terrific balan...
486    Just got this order and it is ok. A bit light ...
556    DEfintely not as tasty as the Madhouse Munchie...
571    With Kettle Chips, you really have to be caref...
574    I'm addicted to salty and tangy flavors, so wh...
602    As an Oregonian, I make a point of sharing the...
603    I'm addicted to salty and tangy flavors, so wh...
635    I want to like Kettle because they contain no ...
649    So I got this and tasted it strait out of the ...
653    If you want to find a good flavor substitute f...
712    My husband (who, being M

In [24]:

# Step 4: Create List of Three Sentences

sentences = [
    "This olive oil is wonderful and very light on the stomach.",
    "The packaging was broken and let too much light inside the box.",
    "I prefer this brand because it is a light and healthy snack."
]


In [25]:

# Step 5: Vectorization Engine

vectorizer = CountVectorizer()

document_term_matrix = vectorizer.fit_transform(sentences)

dense_matrix = document_term_matrix.toarray()

print(dense_matrix)


[[1 0 0 0 0 0 0 1 0 0 1 0 1 1 1 0 0 0 1 1 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 0 1 1 1 0 0 0 1 0 0 0 2 0 1 0 1 0]
 [1 1 0 1 0 1 0 1 1 0 1 0 0 0 0 0 1 1 0 0 1 0 0 0 0]]


In [26]:

# Step 6: Vector Slicing

vec_1 = dense_matrix[0]
vec_2 = dense_matrix[1]
vec_3 = dense_matrix[2]

print(vec_1)
print(vec_2)
print(vec_3)


[1 0 0 0 0 0 0 1 0 0 1 0 1 1 1 0 0 0 1 1 1 0 1 0 1]
[1 0 1 0 1 0 1 0 0 1 1 1 0 0 0 1 0 0 0 2 0 1 0 1 0]
[1 1 0 1 0 1 0 1 1 0 1 0 0 0 0 0 1 1 0 0 1 0 0 0 0]


In [27]:

# Step 7: Similarity Mathematics

similarity_1_2 = np.dot(vec_1, vec_2)

similarity_1_3 = np.dot(vec_1, vec_3)


In [28]:

# Step 8: Console Output

print("Sentence 1 vs Sentence 2 (Different Contexts)")
print("Similarity Score:", similarity_1_2)

print("Sentence 1 vs Sentence 3 (Similar Contexts)")
print("Similarity Score:", similarity_1_3)


Sentence 1 vs Sentence 2 (Different Contexts)
Similarity Score: 4
Sentence 1 vs Sentence 3 (Similar Contexts)
Similarity Score: 4
